# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [ ]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000018D63594D90>, toplevel='numpy')>

## What is Array?

![](image/array.png)

In [ ]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [ ]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [ ]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [ ]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v.shape

(5,)

In [ ]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape

(2, 3)

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [ ]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [ ]:
a = [1,2,3]

In [ ]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [ ]:
v.shape

(5,)

In [ ]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [ ]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [ ]:
one_dimension = np.array([1, 2, 3])
one_dimension

array([1, 2, 3])

In [ ]:
one_dimension.shape

(3,)

In [ ]:
two_dimension = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

two_dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
two_dimension.shape

(3, 3)

In [ ]:
three_dimension = np.array([[[1, 2, 3, 5],
                          [4, 5, 6, 6],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]],
                         
                         [[1, 2, 3, 8],
                          [4, 5, 6, 8],
                          [7, 8, 9, 8],
                          [7, 8, 9, 8]]])

# Print hasil
three_dimension

array([[[1, 2, 3, 5],
        [4, 5, 6, 6],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]],

       [[1, 2, 3, 8],
        [4, 5, 6, 8],
        [7, 8, 9, 8],
        [7, 8, 9, 8]]])

In [ ]:
three_dimension.shape

(4, 4, 4)

In [ ]:
ones = np.ones((7, 7), dtype=int)

# Print ones
ones

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [ ]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_matrix.shape

(5,)

In [ ]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
zeros_matrix2.shape

(5, 2)

### Matrix ones

In [ ]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [ ]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

2. Create the following matrix
![ex1_2.JPG](attachment:ex1_2.JPG)

3. Create a 2D matrix with size of 10

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

5. Make the following arrays from zeros arrays and with for loops
![ex1_5.JPG](attachment:ex1_5.JPG)

### Using array-generating functions

**arange**

In [ ]:
# create a range

x = np.arange(10)

x

In [ ]:
a = []
for i in range(10):
    a.append(i)
a

In [ ]:
# create a range

x = np.arange(10, 20)

x

In [ ]:
# create a range

x = np.arange(10, 20, 2)

x

In [ ]:
x = np.arange(-1, 1, 0.1)

x

#### linspace

In [ ]:
np.linspace(0, 10, 10)

#### random data

In [ ]:
from numpy import random

In [ ]:
random.rand(5,5)

In [ ]:
x = random.randn(5,5)
x

In [ ]:
x.dtype

In [ ]:
x = np.ones(2, dtype = np.int64)
x

In [ ]:
random.randint(10)

In [ ]:
random.randint(2, 10, size=4)

In [ ]:
random.randint(2, 10, size=(4,2,2))

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.